image: java:latest

stages:
  - build
  - test
  - artifact_page

build:
  stage: build
  script:
    - ./gradlew clean assemble
    - ./gradlew javadoc
  artifacts:
    paths:
      - build/docs/javadoc
    expire_in: 1 week

test:
  stage: test
  script:
    - ./gradlew clean test
  artifacts:
    paths:
     - build/reports/tests/test/
    expire_in: 1 week

pages:
  stage: project_page
  script:
    - ./gradlew clean test javadoc
    - cp -r build/docs/javadoc public/javadoc
    - cp -r build/reports/tests/test/ public/test
  artifacts:
    paths:
    - public
  only:
  - master
